valid_payload = {
    "genre": "F",
    "statut_marital": "Célibataire",
    "departement": "Ressources Humaines",
    "poste": "Manager",
    "domaine_etude": "Ressources Humaines",
    "frequence_deplacement": "Ocasionnel",
    "heure_supplementaires": False,
    "evolution_cat_evol": "hausse",
    "categorie_employe": "employe_nouveau_poste_interne",
    "satisfaction_employee_nature_travail": 3,
    "nombre_participation_pee": 1,
    "ecart_note_evaluation": 0,
    "revenu_mensuel": 3000,
    "distance_domicile_travail": 10,
    "satisfaction_globale": 3.5,
    "niveau_education": 2,
    "note_evaluation_actuelle": 4,
    "satisfaction_employee_equipe": 3,
    "age": 35,
    "revenu_par_annee_experience_interne": 2571,
    "satisfaction_employee_equilibre_pro_perso": 3,
    "nombre_experiences_precedentes": 2,
    "annees_dans_l_entreprise": 5,
    "nb_formations_suivies": 1,
    "revenu_par_annee_experience_totale": 2117,
    "ratio_sans_promotion": 1,
    "satisfaction_employee_environnement": 3,
    "exp_hors_entreprise": 4,
    "mobilite_promotion": 1,
    "annees_depuis_la_derniere_promotion": 2}
